# Generated by Django 4.2 on 2024-06-29 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=16)),
                ('offset', models.IntegerField()),
                ('offset_dst', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.timezone'),
        ),
    ]
