# Generated by Django 4.2 on 2024-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_programlanguage_alter_submission_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='test_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
