# Generated by Django 4.2 on 2024-07-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_problem_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='location',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
