# Generated by Django 4.2 on 2024-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_timezone_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='offset_dst',
            field=models.IntegerField(),
        ),
    ]
