# Generated by Django 4.2 on 2024-07-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_timezone_offset_dst'),
    ]

    operations = [
        migrations.AddField(
            model_name='programlanguage',
            name='compile_args',
            field=models.CharField(default=2, max_length=64),
            preserve_default=False,
        ),
    ]
