# Generated by Django 4.2 on 2024-07-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_programlanguage_compile_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_access_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_ip',
            field=models.BinaryField(null=True),
        ),
    ]
