# Generated by Django 4.2 on 2024-07-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_userprofile_last_access_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pdf',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
