# Generated by Django 4.2 on 2024-07-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_problem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
    ]
