# Generated by Django 4.2 on 2024-07-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_submission_memory_alter_submission_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='testcase',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
