# Generated by Django 4.2 on 2024-07-17 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_group_tournament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='participant',
            new_name='participants',
        ),
    ]
