# Generated by Django 4.2 on 2024-07-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_group_creators_group_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num_match',
            field=models.IntegerField(default=0),
        ),
    ]
