# Generated by Django 4.2 on 2024-07-22 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_group_num_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
        ),
    ]
