# Generated by Django 4.2 on 2024-07-23 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_round_first_user_round_second_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='problem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.problem'),
            preserve_default=False,
        ),
    ]
