# Generated by Django 4.2 on 2024-07-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_round_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='second_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='first_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='second_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('F', 'First Win'), ('S', 'Second Win'), ('D', 'Draw'), ('Q', 'In Queue')], default='D', max_length=1),
        ),
    ]
