# Generated by Django 4.2 on 2024-07-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_match_first_score_match_second_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('F', 'First Win'), ('S', 'Second Win'), ('D', 'Draw'), ('Q', 'In Queue')], default='Q', max_length=1),
        ),
    ]
