# Generated by Django 4.2 on 2024-07-25 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RTE', 'Runtime Exception'), ('IR', 'Invalid Return'), ('OLE', 'Output Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('TLE', 'Time Limit Exceeded'), ('IE', 'Internal Error'), ('CE', 'Compile Error'), ('AB', 'Aborted'), ('QU', 'In Queue'), ('PR', 'Processing')], default='QU', max_length=3),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('RTE', 'Runtime Exception'), ('IR', 'Invalid Return'), ('OLE', 'Output Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('TLE', 'Time Limit Exceeded'), ('IE', 'Internal Error'), ('CE', 'Compile Error'), ('AB', 'Aborted'), ('QU', 'In Queue'), ('PR', 'Processing')], default='AB', max_length=3),
        ),
    ]
