# Generated by Django 4.2 on 2024-07-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_submission_status_alter_testcaseresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
