# Generated by Django 4.2 on 2024-07-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_tournament_end_combat_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('F', 'First Win'), ('S', 'Second Win'), ('D', 'Draw'), ('I', 'In Progress'), ('N', 'Not Started')], default='N', max_length=1),
        ),
    ]
