# Generated by Django 4.2 on 2024-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_round_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('N', 'Not Started'), ('I', 'In Progress'), ('D', 'Done')], default='N', max_length=1),
        ),
    ]
