# Generated by Django 4.2 on 2024-07-29 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_group_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_data',
        ),
        migrations.AddField(
            model_name='programlanguage',
            name='extension',
            field=models.CharField(default='cpp', max_length=3),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_data', models.FileField(blank=True, null=True, upload_to='')),
                ('checker', models.FileField(blank=True, null=True, upload_to='')),
                ('generator', models.FileField(blank=True, null=True, upload_to='')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.testdata'),
        ),
    ]
