# Generated by Django 4.2 on 2024-07-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_problem_test_data_programlanguage_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='seed_generator',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='testdata',
            name='type',
            field=models.CharField(choices=[('R', 'Raw Test'), ('G', 'Generator')], default='G', max_length=1),
        ),
    ]
