# Generated by Django 4.2 on 2024-07-29 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_testdata_seed_generator_testdata_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='checker',
            new_name='referee',
        ),
    ]
