# Generated by Django 4.2 on 2024-07-30 03:29

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_rename_checker_testdata_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='generator',
            field=models.FileField(blank=True, null=True, upload_to=api.models.generator_path),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='referee',
            field=models.FileField(blank=True, null=True, upload_to=api.models.referee_path),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='seed_generator',
            field=models.FileField(blank=True, null=True, upload_to=api.models.seed_generator_path),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='test_data',
            field=models.FileField(blank=True, null=True, upload_to=api.models.test_data_path),
        ),
        migrations.CreateModel(
            name='DefaultSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
                ('submission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.submission')),
            ],
        ),
    ]
