# Generated by Django 4.2 on 2024-07-30 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0034_alter_match_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Q', 'Request'), ('A', 'Accept'), ('R', 'Reject'), ('C', 'Cancel')], default='Q', max_length=1)),
                ('first_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chanllenge_first_user', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
                ('second_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='chanllenge_second_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
