# Generated by Django 4.2 on 2024-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_challenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='time',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='total_point',
        ),
        migrations.AddField(
            model_name='submission',
            name='log',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('CE', 'Compile Error'), ('CS', 'Compile Success'), ('QU', 'In Queue'), ('PR', 'Processing')], default='QU', max_length=3),
        ),
        migrations.AlterField(
            model_name='testcaseresult',
            name='status',
            field=models.CharField(choices=[('CE', 'Compile Error'), ('CS', 'Compile Success'), ('QU', 'In Queue'), ('PR', 'Processing')], default='AB', max_length=3),
        ),
    ]
