# Generated by Django 4.2 on 2024-07-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_submission_memory_remove_submission_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='log',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
