# Generated by Django 4.2 on 2024-07-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_submission_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='log',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
