# Generated by Django 4.2 on 2024-08-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_programlanguage_compile_args'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='code',
            new_name='source',
        ),
    ]
