# Generated by Django 4.2 on 2024-08-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_rename_code_submission_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
