# Generated by Django 4.2 on 2024-08-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_match_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='log',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
