# Generated by Django 4.2.14 on 2024-08-04 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_alter_submission_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.round'),
        ),
    ]
