# Generated by Django 4.2.14 on 2024-08-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_challenge_round'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='round',
        ),
        migrations.AddField(
            model_name='round',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.challenge'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(choices=[('Q', 'Request'), ('I', 'In Progress'), ('D', 'Done'), ('R', 'Reject'), ('C', 'Cancel')], default='Q', max_length=1),
        ),
    ]
